baseurl: /
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"
encoding: utf-8
markdown: rdiscount
name: Yoyo
description: Mr.Curiosity
url: https://Robinyao.github.io
avatar: https://avatar.duoshuo.com/avatar-50/353/251940.jpg
