baseurl: /
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"
encoding: utf-8
markdown: kramdown
name: Yoyo
description: Mr.Curiosity
url: https://Robinyao.github.io
avatar: /assets/HeavenKnows-big.jpg
